repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff check
        entry: uv run --no-sync ruff check
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: Ruff format check
        entry: uv run --no-sync ruff format --check
        language: system
        types_or: [python, pyi]
